// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfdwyhuiygpglkxtiamr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmZHd5aHVpeWdwZ2xreHRpYW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDc0NzAsImV4cCI6MjA2MjgyMzQ3MH0.J5v69JMHEXsvfPuLxduWJMXQNevZDLdw0lmQo56CUgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);